Traceback (most recent call last):
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/dang/miniforge3/envs/idaes-conn-py3.12/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# same as above, but the model is built first then provided
from idaes_connectivity.tests import example_flowsheet

basic_model = example_flowsheet.build()
conn = Connectivity(input_model=basic_model.fs)
display_connectivity(conn, jb=True")
------------------


[0;36m  Cell [0;32mIn[3], line 6[0;36m[0m
[0;31m    display_connectivity(conn, jb=True")[0m
[0m                                      ^[0m
[0;31mSyntaxError[0m[0;31m:[0m unterminated string literal (detected at line 6)


